#!/bin/bash

set -e

############################################################
## Logging functions
############################################################
INFO() { echo "INFO: $*"; }
WARN() { echo "WARN: $*"; }
ERRO() { echo "ERRO: $*"; exit 1; }

INFO "Adding i386/x86 architecture"
sudo dpkg --add-architecture i386 || ERRO "Can't add architecture"
sudo apt update -y || WARN "Can't update"
sudo apt upgrade -y || WARN "Can't update"

INFO "Installing wget and gpg, just in case it isnt"
sudo apt install wget gpg -y

INFO "Installing qemu for x86 emulation"
sudo apt install -y qemu-user-static

INFO "Adding http/https transport to apt"
sudo apt install -y apt-transport-https || ERRO "Can't install apt-transport-https"

INFO "Adding sources"
echo "deb https://dl.winehq.org/wine-builds/debian/ stretch main" | sudo tee /etc/apt/sources.list.d/wine.list || ERRO "Can't add apt list"
wget -q --show-progress https://dl.winehq.org/wine-builds/winehq.key -O- | sudo apt-key add - || ERRO "Can't add key"
sudo apt update -y || WARN "Can't update"
sudo apt upgrade -y || WARN "Can't update"

INFO "Installing wine"
sudo apt install -y --install-recommends winehq-staging:i386 || ERRO "Can't Install wine"
sudo apt install -y --install-recommends winetricks:i386 || ERRO "Can't Install winetricks"

INFO "Installing make"
sudo apt install -y make || ERRO "Can't install make"

make install

leagueoflegends install